### ISSUE TITLE
Make PWRTelegram installation script great (and free) again

### ISSUE THREAD

**Issue by MarcoBuster** [pwrtelegram/pwrtelegram-backend#1]
Please <3

**Comment by MarcoBuster** [comment]
This is so annoying

**Comment by danog** [comment]
GIVE ME DA $$$$$$$$$++++++++++++++++++++

**Comment by MarcoBuster** [comment]
An installation script for an open source project should be open source

**Comment by hexbug** [comment]
I've already paid 10$ please give me the install scripts
